[package]
name = "tab-test"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "tab-test"
path = "src/main.rs"

[dependencies]
egui.workspace = true
egui-wgpu.workspace = true
egui-winit.workspace = true
wgpu.workspace = true
winit.workspace = true
pollster = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
anyhow = { workspace = true }
