[package]
name = "retained-scene-test"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "retained-scene-test"
path = "src/main.rs"

[dependencies]
wgpu.workspace = true
winit.workspace = true
pollster = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
anyhow = { workspace = true }
bytemuck = { workspace = true }
glam = { workspace = true }
wgsl-sdf = { workspace = true }
